Create a base popup and the profile successfully created popup - CAS-67
wolfpackdigitalapps/cashli-android pull request #12
Opened 2023-04-04 07:17 UTC by valentinbrad-wolfpack

2023-04-04 10:44 UTC, andreihandra approved these changes

2023-04-05 10:36 UTC, mihai-wolfpack requested changes

2023-04-05 10:36 UTC, mihai-wolfpack commented on app/src/main/java/com/wolfpackdigital/cashli/shared/utils/views/PopupDialog.kt
> +        if (seconds > 0) binding.tvTimer.text = seconds.toString()
Would add `{}` to make the code more readable

2023-04-05 10:36 UTC, mihai-wolfpack commented on app/src/main/java/com/wolfpackdigital/cashli/shared/utils/views/PopupDialog.kt
> +class PopupDialog(
I would create a data class that holds all the parameters for the bindings and set the variables via xml databinding instead of manually applying them in the `setupViews()`

2023-04-05 10:36 UTC, mihai-wolfpack commented on app/src/main/java/com/wolfpackdigital/cashli/shared/utils/views/PopupDialog.kt
> +        when (context) {
```
when {
    context is AppCompatActivity && !context.isFinishing -> dialog.show()
    else -> dialog.dismiss()
}
```

2023-04-07 04:32 UTC, mihai-wolfpack approved these changes

2023-04-07 07:03 UTC, merged