Feature/cas 137 change password
wolfpackdigitalapps/cashli-android pull request #42
Opened 2023-05-16 15:30 UTC by mihai-wolfpack

2023-05-16 19:42 UTC, valentinbrad-wolfpack requested changes

2023-05-16 19:42 UTC, valentinbrad-wolfpack commented on app/src/main/res/values-es/strings.xml
> +    <string name="change_password_passwords_must_match">Passwords much match.</string>
there is a typo "much" in all strings files

2023-05-16 19:42 UTC, valentinbrad-wolfpack commented on app/src/main/res/layout/fr_change_password.xml
> +                android:id="@+id/btn_continue"
btn_continue overlaps the et_confirm_new_password on small devices when the keyboard is opened

2023-05-16 19:42 UTC, valentinbrad-wolfpack commented on app/src/main/res/values/strings-no-translation.xml
> +    <string name="password_hint" translatable="false">********</string>
Check with PO and QA which hint should we use for password input fields. In design is with asterisks but on other screens the "type here" hint is used. Maybe you can make it uniform on all screens

2023-05-16 19:42 UTC, valentinbrad-wolfpack commented on app/src/main/java/com/wolfpackdigital/cashli/data/remote/api/common/RefreshTokenInterceptor.kt
> +        if (response.request.url.pathSegments.last() == CHANGE_PASSWORD_LAST_SEGMENT) {
why is this needed? just curious 😄

2023-05-16 19:42 UTC, valentinbrad-wolfpack commented on app/src/main/java/com/wolfpackdigital/cashli/data/remote/api/common/AuthenticationInterceptor.kt
> +    removeHeader(AUTHORIZATION)
is this needed? "header" fun should replace an existing header with the same name

2023-05-17 06:43 UTC, mihai-wolfpack commented on app/src/main/java/com/wolfpackdigital/cashli/data/remote/api/common/RefreshTokenInterceptor.kt
> +        if (response.request.url.pathSegments.last() == CHANGE_PASSWORD_LAST_SEGMENT) {
This is used because the api endpoint for change passwords returns a 401 error code "unauthorized" in case the credentials are wrong, making the refresh token authenticator refresh tokens until Okhttp returns an error for follow-up requests

2023-05-17 06:44 UTC, mihai-wolfpack commented on app/src/main/java/com/wolfpackdigital/cashli/data/remote/api/common/AuthenticationInterceptor.kt
> +    removeHeader(AUTHORIZATION)
My bad, forgot it replaces already existing ones 😅

2023-05-17 07:00 UTC, valentinbrad-wolfpack approved these changes

2023-05-17 07:25 UTC, merged